### NumPy 

NumPy is a Linear Algebra Library for Python,NumPy as one of the main building blocks for data science. It is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. 

It provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

The most important object defined in NumPy is an N-dimensional array type called ndarray.
It describes the collection of items of the same type. Items in the collection can be accessed
using a zero-based index.
Every item in an ndarray takes the same size of block in the memory. Each element in ndarray
is an object of data-type object (called dtype).
Any item extracted from ndarray object (by slicing) is represented by a Python object of one
of array scalar types

It is also incredibly fast, as it has bindings to C libraries.

In [ ]:
pip install numpy  # for installation

In [4]:
# Import numpy library

import numpy

Numpy has many built-in functions and capabilities. The most important aspects of Numpy: vectors,arrays,matrices, and number generation.
 
# Numpy Arrays

Numpy arrays essentially come in two ways: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
t= [1,2,3]
t

[1, 2, 3]

In [3]:
import numpy as np

np.array(t)

array([1, 2, 3])

In [4]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Question

Create an array filled with all ones upto 10 elements

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### linspace

Return evenly spaced numbers over a specified interval.

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.arange(0,10,3)

array([0, 3, 6, 9])

### Difference between arange and linspace 

<code>np.linspace</code> allows you to define how many values you get including the specified min and max value.

<code>np.arange</code> allows you to define the stepsize and infers the number of steps.

In [15]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
np.arange(0,10,50)

array([0])

### Eye

Creates an identity matrix

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [19]:
np.random.rand(2)

array([0.05224912, 0.89105397])

In [20]:
np.random.rand(5,5)

array([[0.79827965, 0.8085034 , 0.09030074, 0.92872519, 0.09332611],
       [0.86124833, 0.33259157, 0.01526984, 0.08415991, 0.43239086],
       [0.81156222, 0.92360722, 0.38540104, 0.18233707, 0.08374698],
       [0.93279474, 0.24298776, 0.37060813, 0.10179442, 0.67521521],
       [0.87499433, 0.87946742, 0.28973456, 0.49084199, 0.03391676]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

or

The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution. 

In [21]:
np.random.randn(2)

array([ 0.06070219, -0.26243441])

In [22]:
np.random.randn(5,5)

array([[-0.97425572,  1.0456707 ,  0.72473032,  0.64316762,  0.37109871],
       [-0.08670376, -0.38645904, -0.26446565,  0.33340508, -1.06559804],
       [-0.25856218, -1.08747777, -0.06475465,  1.8030667 ,  0.44887227],
       [-0.03962   , -1.71670739, -1.21643668,  1.87539293, -1.5181049 ],
       [ 0.47331116, -0.95141119,  1.30265389, -0.2899984 , -0.1981487 ]])

### randint

Return random integers from `low` (inclusive) to `high` (exclusive).

In [23]:
np.random.randint(1,100)

65

In [24]:
np.random.randint(1,100,10)

array([88,  4, 55, 67, 96, 90, 49, 74, 14, 98])

In [25]:
# normal is used for Guassian distribution

np.random.normal(1,100,10)

array([  96.54201035,  -87.84216033,  -62.55072033,  -39.95347109,
         72.53488273,  166.63815313, -167.49692014,  140.40530804,
        207.7654325 ,   82.03130105])

## Array Attributes and Methods

In [26]:
arr = np.arange(25)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)
ranarr

array([35, 17, 40, 42, 17, 10, 46, 17, 34,  3])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ranarr

array([35, 17, 40, 42, 17, 10, 46, 17, 34,  3])

In [29]:
ranarr.max()

46

In [30]:
ranarr.argmax()

6

In [31]:
ranarr.min()

3

In [32]:
ranarr.argmin()

9

## Shape and Reshape

The ``shape`` gives a tuple of array dimensions and can be used to change the dimensions of an array.

The ``reshape`` gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

In [33]:
# Vector
b = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24]
c = np.array(b)
c.shape

(25,)

In [34]:
# Notice the two sets of brackets

a=c.reshape(1,25)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
a.shape

(1, 25)

In [36]:
a.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.reshape(25,1).shape

(25, 1)

### Question 

List of intergers 1,2,3,4,5,6,7,8,9 reshape into 3,3

In [ ]:
l=[1,2,3,4,5,6,7,8,9]
c=np.array(l)
p=c.reshape(3,3)
c.shape

### dtype

You can also grab the data type of the object in the array

In [38]:
arr.dtype

dtype('int32')

#### Create an empty array of 3,4 and full array of 3,3 with value 55

In [39]:
x=(np.empty((3,4), dtype=int))
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
y=(np.full((3,3), 55))
y

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

### ``bincount`` is use to get the count of occurances of elements in the array

In [43]:
# Find most frequent value in an array

x=np.array([2,2,3,3,3,2,2,1,5,6,1])
y=np.bincount(x)
y

array([0, 2, 4, 3, 0, 1, 1], dtype=int64)

In [44]:
# max inside the bincount array

y=np.bincount(x).max()
y

4

In [45]:
# max value

y=np.bincount(x).argmax()
y

2

### Question 

Find the max value from the given list

x = [4, 18, 2, 8, 3, 15, 14, 15, 20, 12, 6, 3, 15, 12, 13, 19, 14, 81, 23, 44]
